{
    'name': 'project_dream',
    'author': 'mais alnawa',
    'category': '',
    'version': "17.0.0.1.0",
    'depends': ['base', 'sale_management', 'account', 'mail',
                'website','crm',
                ],
    'data': [
        'security/ir.model.access.csv',
        'security/security.xml',
        'views/base.xml',
        'views/customer.xml',
        'views/owner.xml',
        'views/property_view.xml',
        'views/sale.xml',
        'views/history.xml',
        'views/crm.xml',
        'views/show.xml',
        'views/templates.xml',
        'wizards/wizard.xml',
        'data/sequence.xml',
        "reports/report.xml",

    ],
    'assets': {
        'web.assets_frontend': ['app_one\static\src\property.css',
                                'app_one\static\src\css\style.css',
                                'app_one/static/src/img',
                                'app_one/static/src/html/style.html',

                               ],
        'web.report_assets_common': ['app_one/static/src/font.css'],
    },
    'application': True,
}
